#!/bin/bash
####################script for outputing the corresponding line numbers of given timestamps as inputs (for filtering of graphs)###############################################

if [ $# -ne 2 ]; then
    echo "Usage: $0 full_timestamps_file two_timestamps_file"
    exit 1
fi

full_timestamps="$1" #full_timestamps is the text file where all the timestamps of the uploaded log file are stored ( only timestamps )
two_timestamps="$2" #two_timestamps is the text file where the two timestamps given as inputs are stored in this file, this file is automatically generated and the code where these timestamps stored in this file is written in appy.py

if [ ! -f "$full_timestamps" ] || [ ! -f "$two_timestamps" ]; then
    echo "Error: One or both input files do not exist"
    exit 1
fi

time1=$(head -n 1 "$two_timestamps" | tr -d '\r' | xargs)
time2=$(tail -n 1 "$two_timestamps" | tr -d '\r' | xargs)

line1=0 #to note the corresponding line of given 1st timestamp
line2=0 #to note the corresponding line of given 2ndtimestamp
current_line=0

while IFS= read -r line; do #checking line by line of full timestamps text file
    current_line=$((current_line + 1))
    clean_line=$(echo "$line" | tr -d '\r' | xargs)
    
    if [[ "$clean_line" == "$time1" && $line1 -eq 0 ]]; then
        line1=$current_line
    fi
    
    if [[ "$clean_line" == "$time2" && $line2 -eq 0 ]]; then
        line2=$current_line
    fi

    if [[ $line1 -ne 0 && $line2 -ne 0 ]]; then
        break
    fi
done < "$full_timestamps" 


echo "${line1}" > line_nos.txt #storing the output in line_nos.txt
echo "${line2}" >> line_nos.txt
echo "Line numbers written to line_nos.txt: ${line1},${line2}" #for debugging